/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Chat
         * @description Point d'entrée de conversation avec l'agent Architecto (réponse complète).
         */
        post: operations["chat_api_v1_chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chat/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Chat Stream
         * @description Diffuse la réponse de l'agent (Server-Sent Events).
         *
         *     Évènements émis : `{type:"tool", name, phase}` (activité d'outil),
         *     `{type:"delta", text}` (tokens), puis `{type:"done", thread_id}`,
         *     ou `{type:"error", message}` en cas d'échec.
         */
        post: operations["chat_stream_api_v1_chat_stream_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/knowledge/ingest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ingest
         * @description Ingère des documents téléversés (`.md`, `.txt`, `.pdf`) dans pgvector.
         *
         *     Idempotent par nom de fichier : réingérer un contenu identique est ignoré,
         *     un contenu modifié remplace ses anciens chunks.
         */
        post: operations["ingest_api_v1_knowledge_ingest_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/knowledge/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Sources
         * @description Liste les sources déjà ingérées (les plus récentes d'abord).
         */
        get: operations["list_sources_api_v1_knowledge_sources_get"];
        put?: never;
        post?: never;
        /**
         * Delete Source
         * @description Supprime une source et ses chunks vectoriels.
         */
        delete: operations["delete_source_api_v1_knowledge_sources_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/memory/decisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Decisions
         * @description Décisions d'architecture (ADR) d'un projet, les plus récentes d'abord.
         */
        get: operations["list_decisions_api_v1_memory_decisions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/memory/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Projects
         * @description Projets ayant des décisions enregistrées (les plus récents d'abord).
         */
        get: operations["list_projects_api_v1_memory_projects_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_ingest_api_v1_knowledge_ingest_post */
        Body_ingest_api_v1_knowledge_ingest_post: {
            /** Files */
            files: string[];
        };
        /** ChatRequest */
        ChatRequest: {
            /**
             * Message
             * @description Message de l'utilisateur
             */
            message: string;
            /**
             * Project
             * @description Slug du projet (scope la mémoire long terme)
             * @default
             */
            project: string;
            /**
             * Thread Id
             * @description Identifiant de conversation (mémoire)
             * @default default
             */
            thread_id: string;
        };
        /** ChatResponse */
        ChatResponse: {
            /** Answer */
            answer: string;
            /** Thread Id */
            thread_id: string;
        };
        /** DecisionOut */
        DecisionOut: {
            /** Consequences */
            consequences: string;
            /** Context */
            context: string;
            /** Decision */
            decision: string;
            /** Id */
            id: string;
            /** Status */
            status: string;
            /** Title */
            title: string;
        };
        /** DecisionsList */
        DecisionsList: {
            /** Decisions */
            decisions: components["schemas"]["DecisionOut"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * IngestResult
         * @description Bilan d'une ingestion depuis le client.
         */
        IngestResult: {
            /** Chunks */
            chunks: number;
            /** Processed */
            processed: number;
            /**
             * Rejected
             * @default []
             */
            rejected: string[];
            /** Skipped Empty */
            skipped_empty: number;
            /** Skipped Unchanged */
            skipped_unchanged: number;
        };
        /** ProjectOut */
        ProjectOut: {
            /** Decision Count */
            decision_count: number;
            /** Name */
            name: string;
            /** Slug */
            slug: string;
        };
        /** ProjectsList */
        ProjectsList: {
            /** Projects */
            projects: components["schemas"]["ProjectOut"][];
        };
        /**
         * SourceOut
         * @description Une source ingérée dans la base de connaissances.
         */
        SourceOut: {
            /** Chunk Count */
            chunk_count: number;
            /** Source */
            source: string;
            /** Title */
            title: string;
        };
        /** SourcesList */
        SourcesList: {
            /** Sources */
            sources: components["schemas"]["SourceOut"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    chat_api_v1_chat_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    chat_stream_api_v1_chat_stream_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    ingest_api_v1_knowledge_ingest_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_ingest_api_v1_knowledge_ingest_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_sources_api_v1_knowledge_sources_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourcesList"];
                };
            };
        };
    };
    delete_source_api_v1_knowledge_sources_delete: {
        parameters: {
            query: {
                source: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_decisions_api_v1_memory_decisions_get: {
        parameters: {
            query: {
                project: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DecisionsList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_projects_api_v1_memory_projects_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectsList"];
                };
            };
        };
    };
}
